/**
 * Copyright (C) 2011 Cubeia Ltd <info@cubeia.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.cubeia.firebase.api.action;

import com.cubeia.firebase.api.action.visitor.GameActionVisitor;

/**
 * <p>Request to reserve a seat. This can be sent either directly from
 * a client or indirectly from the filtered join waiting list.</p> 
 *
 * <p>Currently this action will always be generated by the system.</p>
 *
 * @author Fredrik Johansson, Cubeia Ltd
 */
public class ReserveSeatRequestAction extends AbstractPlayerAction {

	private static final long serialVersionUID = 1L;
	
	private int seatId; 
	
	/** Flag if the request was generated by the system */
	private boolean waitingList = false;
	
	/** This is used when the request is associated with a waiting list */
	private long waitingListId = -1;

	private int waitingListSequence;
	
	public ReserveSeatRequestAction(int playerId, int tableId, int seatId) {
		super(playerId, tableId);
		this.seatId = seatId;
	}
	
	public void visit(GameActionVisitor visitor) {
		visitor.visit(this);
	}	


	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
    public String toString() {
		return "ReserveSeatRequest: playerId: " + getPlayerId() + " table: "+getTableId()+" seatId: " + seatId;
	}

	public void setSeatId(int seatId) {
		this.seatId = seatId;
	}
	
	public int getSeatId() {
		return seatId;
	}

	/**
	 * True if this request has been generated by the internal waiting list. 
	 * This is needed by the system to differentiate between directly generated
	 * requests and waiting list requests.
	 * 
	 * @return
	 */
	public boolean isWaitingList() {
		return waitingList;
	}

	public void setWaitingList(boolean waitingList) {
		this.waitingList = waitingList;
	}

	/**
	 * Gets the identifier for the waiting list generating this
	 * request, if applicable.
	 * 
	 * @return
	 */
	public long getWaitingListId() {
		return waitingListId;
	}

	public void setWaitingListId(long waitingListId) {
		this.waitingListId = waitingListId;
	}

	public void setWaitingListSequence(int seq) {
		this.waitingListSequence = seq;
	}

	/**
	 * @return The waiting list sequence id, if known
	 */
	public int getWaitingListSequence() {
		return waitingListSequence;
	}
}
