/**
 * Copyright (C) 2011 Cubeia Ltd <info@cubeia.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.cubeia.firebase.api.action;

import com.cubeia.firebase.api.action.visitor.GameActionVisitor;


public class UnWatchAction extends AbstractPlayerAction {

	private static final long serialVersionUID = 7894608084259545327L;
	
	private int status;
	
	/**
	 * Flag for who has generated the request.
	 * 
	 * If the request is by server, then it has been generated by
	 * a cleanup procedure (reaper etc) and we should not return a 
	 * response to the client.
	 */
	private boolean byServer = false;
	
	public UnWatchAction(int playerId, int tableId) {
		super(playerId, tableId);
	}

	public void visit(GameActionVisitor visitor) {
		visitor.visit(this);
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public boolean isByServer() {
		return byServer;
	}

	public void setByServer(boolean byServer) {
		this.byServer = byServer;
	}

}
